version: '3.9'

services:
  optimizer:
    build:
      context: ./optimizer
    image: optimizer
    container_name: cobs-optimizer
    ports:
      - "8000:80"
    restart: unless-stopped

  app:
    image: node:20
    container_name: cobs-app
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
    environment:
      - OPTIMIZER_URL=http://optimizer:80
    ports:
      - "3000:3000"
    depends_on:
      - optimizer
    restart: unless-stopped
